<?php
/** @var CampaignLabel $viewModel */

use Impact\Campaign\ViewModel\CampaignLabel;

$viewModel = $block->getCampaignViewModel();
$campaignsData = $viewModel->getCampaignLabel($block->getProduct());
?>

<?php if (!empty($campaignsData)): ?>
    <?php foreach ($campaignsData as $campaignData): ?>
        <div class="campaign-label">
            <span style="background-color:<?= $campaignData['color'] ?>;"><?= $campaignData['title'] ?></span>
        </div>
    <?php endforeach;?>
<?php endif; ?>
